### ISSUE TITLE
Bug in union?

### ISSUE THREAD

**Issue by avishaiben** [amccaugh/phidl#106]
Hey Adam,

I found that Union isn't managing to unionize some polygons. Not sure why yet. I am showing below an example.

![image](https://user-images.githubusercontent.com/63114579/119385118-8e0a3e00-bc7a-11eb-9280-ffa646aa7afb.png)

**Comment by amccaugh** [comment]
Hi @avishaiben , would you be able to post example code?  It's not clear what might be going wrong just from the images
