### ISSUE TITLE
PHIDL won't update in anaconda navigator

### ISSUE THREAD

**Issue by georgiosauce** [amccaugh/phidl#113]
Stuck on version 1.4.2 despite installing the latest version. Command 'conda list' shows version 1.5.2 but anaconda will only run 1.4.2 and will not show update available therefore cannot use gridsweep function

**Comment by amccaugh** [comment]
Can you paste the commands you're using to install/check the version?  For instance

`pip install -U phidl` to install phidl

then inside python running

```
import phidl
print(phidl.__version__)
```

**Comment by georgiosauce** [comment]
conda list shows version 1.5.2 in terminal window. import phidl -> print(phidl.__version__) in Jupyter notebook gives 1.4.2

**Comment by georgiosauce** [comment]
Also I get this message despite phidl being listed in conda list

PackagesNotFoundError: The following packages are not available from current channels:

  - phidl

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by georgiosauce** [comment]
Got it to work, I was in the wrong directory when installing

**Comment by amccaugh** [comment]
I see -- phidl is not uploaded to `conda`, so instead of using that you should do the following

1. Click Open terminal from environment
![image](https://user-images.githubusercontent.com/2075083/129396978-e6ac704e-f414-4cd5-b874-6d9b60c9a2c6.png)
2. In the terminal run `pip install -U phidl`
