### ISSUE TITLE
Glitch when using extrude on a spiral path

### ISSUE THREAD

**Issue by DanHickstein** [amccaugh/phidl#116]
Thanks for all of your great work developing the Phidl package! I have only been using it for the past week, but I've really been enjoying the package and your nice documentation.

I encountered an issue with using the `extrude` function on a spiral path. Basically, it is possible it get a large glitch in object that is created:

![image](https://user-images.githubusercontent.com/1107796/137050349-802c2aae-309a-48df-b420-6fca233da478.png)

I used this code to generate this image:
```python
import phidl
import phidl.path as pp

P = pp.Path()
P.append(pp.spiral(num_turns=15.5, gap=5, inner_gap=200, num_pts=8000))
D = P.extrude(width=1)
phidl.quickplot(D)
```

The glitch only occurs for certain values of gap/inner_gap/width. Sometimes the glitch will appear in the center of the spiral.

Thanks!

**Comment by amccaugh** [comment]
Thank you for the bug report & especially for the example code -- I was able to reproduce the issue in 1.6.0.  I'm guessing it has something to do with an incorrectly appended point between the inner curve and the spiral, seeing as it happens where the spiral transitions to the S-curve (or at the S-curve central joint).

I'll take a look at it in the next couple days and see if I can come up with a fix
