### ISSUE TITLE
CrossSection extrude - wrong named parameter

### ISSUE THREAD

**Issue by gyger** [amccaugh/phidl#119]
Path.extrude no longer has a argument cross_section, but it is now called width and can be a cross-section. This needs to be adapted in CrossSection.extrude.

**Comment by amccaugh** [comment]
Good catch, thanks @gyger.  This should be fixed on `dev` (and a unit test in place to prevent it from happening again) with commit 482658e

**Comment by gyger** [comment]
Great, thanks for that fast fix and congrats on your publication. :) PHIDL really became the just right tool, much more flexible than the Foundry PDK based tools, but more helpful than gdspy alone.

**Comment by amccaugh** [comment]
Thanks, I'm glad it's been useful!
