### ISSUE TITLE
DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`

### ISSUE THREAD

**Issue by flaport** [amccaugh/phidl#121]
Hey, as of numpy 1.20 I'm getting this warning:

```python
DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
```

I could open a PR for this, but the changes necessary to solve this problem are so trivial it's probably not worth it. I think you'd need to swap np.float by np.float64 (or just float) in 3 places in device_layout.py.

**Comment by amccaugh** [comment]
Thanks for the bug report, it should be fixed in 3f4359d
