### ISSUE TITLE
CrossSections are unnamed in .gds file

### ISSUE THREAD

**Issue by dandomi** [amccaugh/phidl#125]
Hello,

Following the tutorial for "Transitioning between cross-sections" and appending a command to write a GDS file results in the paths being "Unnamed" in the GDS cell tree. Is this a bug or am I doing something wrong?

from phidl import Device, Layer, LayerSet, Path, CrossSection
from phidl import quickplot as qp
import numpy as np
import phidl.geometry as pg
import phidl.path as pp

P = Path()
P.append( pp.arc(radius = 10, angle = 90) )   # Circular arc
P.append( pp.straight(length = 10) )          # Straight section
P.append( pp.euler(radius = 3, angle = -90) ) # Euler bend (aka "racetrack" curve)
P.append( pp.straight(length = 40) )
P.append( pp.arc(radius = 8, angle = -45) )
P.append( pp.straight(length = 10) )
P.append( pp.arc(radius = 8, angle = 45) )
P.append( pp.straight(length = 10) )

# Create our first CrossSection
X1 = CrossSection()
X1.add(width = 1.2, offset = 0, layer = 2, name = 'wg', ports = ('in1', 'out1'))
X1.add(width = 2.2, offset = 0, layer = 3, name = 'etch')
X1.add(width = 1.1, offset = 3, layer = 1, name = 'wg2')

# Create the second CrossSection that we want to transition to
X2 = CrossSection()
X2.add(width = 1, offset = 0, layer = 2, name = 'wg', ports = ('in2', 'out2'))
X2.add(width = 3.5, offset = 0, layer = 3, name = 'etch')
X2.add(width = 3, offset = 5, layer = 1, name = 'wg2')

# To show the cross-sections, let's create two Paths and create Devices by extruding them
P1 = pp.straight(length = 5)
P2 = pp.straight(length = 5)
WG1 = P1.extrude(X1)
WG2 = P2.extrude(X2)

# Place both cross-section Devices 
D = Device()
wg1 = D << WG1
wg2 = D << WG2
wg2.movex(7.5)

# Create the transitional CrossSection
Xtrans = pp.transition(cross_section1 = X1,
                        cross_section2 = X2,
                        width_type = 'sine')
# Create a Path for the transitional CrossSection to follow
P3 = pp.straight(length = 15)
# Use the transitional CrossSection to create a Device
WG_trans = P3.extrude(Xtrans)

D = Device()
wg1 = D << WG1 # First cross-section Device
wg2 = D << WG2
wgt = D << WG_trans

wgt.connect('in2', wg1.ports['out1'])
wg2.connect('in2', wgt.ports['out1'])

qp(D)

D.write_gds('TestGDS')
![Capture](https://user-images.githubusercontent.com/60673522/155589581-bef914a8-9a00-457e-b9f2-c8c19eae31cd.PNG)

**Comment by amccaugh** [comment]
No worries, you're not doing anything wrong -- this is just a simple naming issue.  It won't actually affect your design, but I've corrected it in cf3f582 , and it should be available in the next update.
