### ISSUE TITLE
non-manhattan connect

### ISSUE THREAD

**Issue by joamatab** [amccaugh/phidl#153]
How can we connect two structures that have non-manhattan connections with offgrid ports?

```
import phidl.path as pp
import phidl.device_layout as pd


if __name__ == "__main__":
    c = pd.Device('non-manhattan-connect')
    b = c << pg.arc(theta=30)
    s = c << pg.straight(size=(1, 1))
    s.connect(1, b.ports[2])
```

![image](https://user-images.githubusercontent.com/4514346/175093549-d60f5c23-6cdd-4931-9e9f-55b71c48fdd3.png)

**Comment by joamatab** [comment]
one possible solution is to flatten

```
    c = pd.Device('non-manhattan-connect')
    b = c << pg.arc(theta=30)
    s = c << pg.straight(size=(0.5, 1))
    s.connect(1, b.ports[2])
    c = c.flatten()
```

**Comment by amccaugh** [comment]
Interesting, if it works flattened that suggests it's not an issue with the routing, but just a more common integer-precision error.  If you save the GDS with a precision of e.g. 1e-5 (instead of 1e-3), is it less bad?

**Comment by joamatab** [comment]
1e-10 looks better

![image](https://user-images.githubusercontent.com/4514346/175209110-cbf39145-5c45-4105-962f-be44bc305a6c.png)


the default is 1e-9

**Comment by joamatab** [comment]
We solved this issue in gdsfactory

https://github.com/gdsfactory/gdsfactory/pull/479

now we can even work with offgrid ports

**Comment by amccaugh** [comment]
How do you avoid this exactly? I assume you can snap the port itself to the grid, but when you allow arbitrary rotations (e.g. not just 90/180/270 manhattan rotations), integer rounding errors are inevitable.  See for example this example -- left is the unsnapped port, right is the snapped port.  There's no grid snapping is able to satisfactorily align the two polygons:

<img width="728" alt="image" src="https://user-images.githubusercontent.com/2075083/175784228-aabfb5c3-e747-47fc-abab-c925c4b4bd57.png">
