### ISSUE TITLE
How can you replace a reference that has already been added?

### ISSUE THREAD

**Issue by joamatab** [amccaugh/phidl#154]
How can you replace a reference that has already been added?

why does this not work?

This code replaces an ellipse with a ring

```
import phidl.device_layout as pd
import phidl.geometry as pg
from phidl import quickplot2 as qp


c = pd.Device()
c1 = c << pg.ellipse()
c2 = pg.ring()
c1.parent = c2
qp(c)
```

but the plot still shows the ellipse

**Comment by amccaugh** [comment]
PR has been merged, thanks!
