### ISSUE TITLE
lazy load matplotlib

### ISSUE THREAD

**Issue by joamatab** [amccaugh/phidl#158]
Hi Adam,

i rarely use the matplotlib ploter from phidl, so making  `import matplotlib` as a lazy loaded module could save almost 3 seconds when importing the phidl module

![image](https://user-images.githubusercontent.com/4514346/178360688-ab3765e0-7782-4ede-bd64-b6b7bce65418.png)

**Comment by amccaugh** [comment]
Done! Thanks for the contribution @joamatab , we'll push a new release out in the next few days
