### ISSUE TITLE
geometry.union does not accept list

### ISSUE THREAD

**Issue by gyger** [amccaugh/phidl#169]
geometry.union does not accept a list of devices contrary to what is written in the documentation.

**Comment by amccaugh** [comment]
Good catch, I'll try to get that fixed in the new few days

**Comment by amccaugh** [comment]
Unfortunately I haven't had any time to implement a fix for this, so for hte moment I'll just correct the documentation.  I've added a TODO for future work, in particular these two TODOs should be extremely easy to implement if I get around to implementing `Group.get_polygons()`:

```
# Add Group.get_polygons()
    # Allow Boolean to use Groups
    # Allow pg.union to use Groups
```
