### ISSUE TITLE
Strange artifacts from path -> CrossSection -> extrude

### ISSUE THREAD

**Issue by basnijholt** [amccaugh/phidl#173]
See the following code:
```python
import phidl.path as pp
from phidl.device_layout import CrossSection
import numpy as np
from phidl.quickplotter import quickplot as qp
import matplotlib.pyplot as plt

points = np.array(
    [
        [-6.6, -13.5],
        [-6.6, -16.5],
        [-38.3, -57.75],
        [-160.0, -59.75],
        [-240.0, -105.0],
        [-240.0, -107.0],
    ],
)

# Show the points
plt.scatter(*points.T)
plt.show()

path = pp.smooth(
    points=points,
    radius=0.005,
    corner_fun=pp.euler,
)
x = CrossSection()
x.add(width=6)
device = path.extrude(x)

qp(device)
```

Which tries to extrude the following points/path:
<img width="851" alt="image" src="https://user-images.githubusercontent.com/6897215/213018995-e2be97a5-b5e7-48d2-9566-34f72a4a426c.png">

<img width="820" alt="image" src="https://user-images.githubusercontent.com/6897215/213019031-537ab4a6-f3bf-4344-96ea-c771c173be1a.png">

And results in:
<img width="837" alt="image" src="https://user-images.githubusercontent.com/6897215/213019070-3536238d-2eaa-45e0-acc4-c83881a8f4c9.png">
with zoom ins:
<img width="848" alt="image" src="https://user-images.githubusercontent.com/6897215/213019175-bf81f222-7f17-4fc7-b89c-7af5166d0231.png">
<img width="814" alt="image" src="https://user-images.githubusercontent.com/6897215/213019251-72c4696e-61ee-44b3-8001-b5249b4cc1e2.png">

I do not expect these artifacts in the corners. Is this my fault or is this a bug?

**Comment by amccaugh** [comment]
Yes, those are a known artifact known as "cusps".  They're the result of trying to take low-radius turns with large width wires, see for instance the first image in https://en.wikipedia.org/wiki/Parallel_curve:

![image](https://user-images.githubusercontent.com/2075083/213027249-7c5a6935-c3fc-48f6-a263-2964b06e3279.png)

There are a variety of algorithms dedicated to "fixing" this, but after a lot of background research I decided to avoid them entirely for two reasons: (1) they're generally very slow, especially in Python, (2) it's not obvious what the proper behavior *should even be* -- depending on who you ask, they might want those corners to just be clipped (leaving a sharp interior angle):

![image](https://user-images.githubusercontent.com/2075083/213027689-70d8238c-50ed-43b0-b7b9-ac665d8353db.png)

or they may want them to be rounded as in a true offset operation:

![image](https://user-images.githubusercontent.com/2075083/213027813-bc3c72c2-d125-47ed-a4e1-032b3faaa260.png)

**Comment by basnijholt** [comment]
Thanks a lot for your reply. 

Could you perhaps point me to some of those algorithms that remove the cusps (one's you are aware of at least)?

**Comment by joamatab** [comment]
Hi Bas,

I tried this in gdsfactory and seems to work  fine

```
import numpy as np
import matplotlib.pyplot as plt
import gdsfactory as gf

points = np.array(
    [
        [-6.6, -13.5],
        [-6.6, -16.5],
        [-38.3, -57.75],
        [-160.0, -59.75],
        [-240.0, -105.0],
        [-240.0, -107.0],
    ],
)

path = gf.path.smooth(
    points=points,
    radius=0.005,
)
x = gf.CrossSection(layer=(1, 0), width=2)
# x = gf.CrossSection(width=2)
c = path.extrude(x)
c.show()
```

**Comment by amccaugh** [comment]
@joamatab that's very interesting -- do you know what's happening differently?  Typically the fixes I've seen for this problem are some kind of union/boolean operation that intrinsically is able to remove these kinds of self-intersections, but they come at a fairly high computational overhead

**Comment by amccaugh** [comment]
@basnijholt I found that searching for the keywords `cusp`, `self-intersection`, `polyline` and `offset` ended up being the most helpful.  These stackexchange answers in particular were illuminating:

* https://math.stackexchange.com/questions/2208468/self-intersection-removal-in-offset-curves
* https://stackoverflow.com/questions/69935520/offsetting-a-polyline-in-one-direction
* https://math.stackexchange.com/a/302101

For instance, one of them points to this paper, which isn't terribly well-written but is helpful to understand the depth/variety of the problem and has some good references: http://www.cs.technion.ac.il/~gershon/papers/offset-compare.pdf .  Other work that seems a bit more robust (but also a little more impenetrable) is this: [An offset algorithm for polyline curves](https://www.researchgate.net/publication/222549414_An_offset_algorithm_for_polyline_curves)

**Comment by amccaugh** [comment]
More to the point -- what's happening where there are cuts in the path that aren't present in the `path.extrude(x)` operation?
