### ISSUE TITLE
Suggest Change to Transition

### ISSUE THREAD

**Issue by TravisAutry** [amccaugh/phidl#179]
Hey,

I just found a bug.  The issue being transition and sleeves not following the transition path. On the transition function it reads

`     offset_fun = _sinusoidal_transition(offset1, offset2)

            if width_type == "sine":
                width_fun = _sinusoidal_transition(width1, width2)
            elif width_type == "linear":
                width_fun = _linear_transition(width1, width2)
            else:
                raise ValueError(
                    "[PHIDL] transition() width_type "
                    + "argument must be one of {'sine','linear'}"
                )`

I think it would be better if 

``     

            if width_type == "sine":
                width_fun = _sinusoidal_transition(width1, width2)
                offset_fun = _sinusoidal_transition(offset1, offset2)
            elif width_type == "linear":
                width_fun = _linear_transition(width1, width2)
                offset_fun = _linear_transition(offset1, offset2)
            else:
                raise ValueError(
                    "[PHIDL] transition() width_type "
                    + "argument must be one of {'sine','linear'}"
                )``

**Comment by amccaugh** [comment]
Interesting, any chance you can try out this change on https://github.com/amccaugh/phidl/issues/177 ?  I'm curious if it might actually solve that problem.

Aside from that, can you describe why it might be better?  I believe I avoided allowing this because it caused some strange artifacts, but that was a while ago.

**Comment by amccaugh** [comment]
Do you have a minimum-working example you can share?

**Comment by loganbvh** [comment]
> Do you have a minimum-working example you can share?

I came across this same issue with the code below:

```python
width = 500
gap = width * 0.5
offset = (width + gap) / 2

X1 = CrossSection()
X1.add(width=width, offset=0, layer=1, name="center", ports=("in", "out"))
X1.add(width=gap, offset=-offset, layer=0, name="left")
X1.add(width=gap, offset=offset, layer=0, name="right")


width = 100
gap = width * 0.5
offset = (width + gap) / 2

X2 = CrossSection()
X2.add(width=width, offset=0, layer=1, name="center", ports=("in", "out"))
X2.add(width=gap, offset=-offset, layer=0, name="left")
X2.add(width=gap, offset=offset, layer=0, name="right")


X = pp.transition(X1, X2, width_type="linear")
P = pp.straight(length=500)
D = P.extrude(X)

qp(D)
```

![image](https://github.com/amccaugh/phidl/assets/20325010/4db0fbe4-07a4-4ae5-acac-83afff65c8dd)

It seems like the fix proposed [above](https://github.com/amccaugh/phidl/issues/179#issue-1728154645) would fix this.

**Comment by loganbvh** [comment]
Makes sense, thanks for the explanation!
