### ISSUE TITLE
Roughness of bends, curves and rings edges

### ISSUE THREAD

**Issue by Ikechi12** [amccaugh/phidl#185]
I have noticed that the edges of bends and curves generated using Phidl are not smooth. This affected the fabricated devices as well.
I have tried a couple of methods:
1. Using paths and increasing the number of points
2. using ring and curve polygons and increasing the angle_resolution.
However, the issue persists.

Below is an image of a section of the device I designed using Phidl:
![image](https://github.com/amccaugh/phidl/assets/84325914/50a1a80e-dcf7-4e32-900a-c7872e8690f5)

Upon zooming, you will see that the curve is not so smooth, 
![image](https://github.com/amccaugh/phidl/assets/84325914/277f9eba-eb7a-4a77-9577-dc28254fee69)
![image](https://github.com/amccaugh/phidl/assets/84325914/3e765400-e051-4be0-bb41-3e5181d04e6a)

Notice that the deviation at the points is sharp and not curved, so the rings are basically polygons with sides equal to the number of points.
![image](https://github.com/amccaugh/phidl/assets/84325914/7cce3de2-58e6-493a-8c21-58be3587b2cc)

After fabrication, the images from the SEM show this roughness:
![image](https://github.com/amccaugh/phidl/assets/84325914/4f36a999-46eb-4759-9189-e0bc56c15430)
![image](https://github.com/amccaugh/phidl/assets/84325914/c00bf4a5-b4f3-4557-86ea-40012347bb9e)

So how can I get the smoothest possible curves and rings using Phidl?

**Comment by amccaugh** [comment]
Hi @Ikechi12 , apologies for the delay in response.  I believe what you want here is *increased* `angle_resolution`, not decreased -- the `angle_resolution` sets the number of degrees per point, so if `angle_resolution = 1`, a full ring will consist of 360 points.  If `angle_resolution = 0.5`, a full ring will consist of 720 points.  For example:

```python
import phidl.geometry as pg

D =  pg.ring(radius = 5, width = 0.5, angle_resolution = 1, layer = 0)
D << pg.ring(radius = 5, width = 0.5, angle_resolution = 0.2, layer = 1)
D.write_gds('rings.gds')
```
`angle_resolution = 1`
![image](https://github.com/amccaugh/phidl/assets/2075083/5f4bb395-e92f-41c9-92c7-8da2383b63ee)

`angle_resolution = 0.2`
![image](https://github.com/amccaugh/phidl/assets/2075083/2f55fb12-79f5-44b2-989d-e8b1a468e593)

**Comment by amccaugh** [comment]
Also, note that *all* structures in GDSII are polygons -- there are no representations of perfect arcs/circles.  By adding a lot of points, however, you can generate curves that should have much higher resolution than what is achievable even with e-beam, so they should look as good as practically possible

**Comment by Ikechi12** [comment]
Thank you @amccaugh
