### ISSUE TITLE
I'm having some problems with it

### ISSUE THREAD

**Issue by ChenyangCao1999** [amccaugh/phidl#202]
import numpy as np
import matplotlib.pyplot as plt
from phidl import Path,Device,Layer,CrossSection
from phidl import quickplot as qp
import phidl.geometry as pg
import phidl.path as pp
P=Path([(20,10), (30,10), (40,30), (50,30), (50,20), (55,20)])
D = P.extrude(0.5)
Via = pg.ellipse(radii = (0.5,0.2), layer = 3)
distances = np.linspace(0, P.length(), 35)
offset = 1
points, angles = P.interpolate(distances, offset)
for (x,y), a in zip(points, angles):
    via = D << Via
    via.rotate(a)
    via.center = x,y
qp(D)

Traceback (most recent call last):
  File "d:\code\2024_5_6.py", line 57, in <module>
    points,angles=P.interpolate(distances,offset)
                  ^^^^^^^^^^^^^
AttributeError: 'Path' object has no attribute 'interpolate'

**Comment by amccaugh** [comment]
Have you upgraded to the latest version of phidl?  `pip install -U phidl`
