### ISSUE TITLE
Possible undesired behavior of `pg.offset`

### ISSUE THREAD

**Issue by EliDoris** [amccaugh/phidl#204]
I've been using a "heal" function to get rid of small gaps that pop up here and there which are presumably caused by rounding errors. This works by doing a `pg.offset()` with a distance of `0.001` (the resolution for the layout) followed by another with a distance of `-0.001`. This, however, has caused additional problems because it seems to move some polygons in x or y by 0.001 in and of itself, likely also due to rounding issues.

I'm not sure if this is a side effect of intended behavior or a bug. Either way, maybe it would be useful to have a built-in heal that does these two operations back-to-back without any rounding steps in between to avoid the issue entirely

**Comment by amccaugh** [comment]
A few things to mention:
* Heal (sometimes called "merge") can usually be accomplished with a boolean "OR" operation where you provide an empty input for the second.
* I strongly recommend using the [KLayout-based boolean/offset functions](https://phidl.readthedocs.io/en/latest/search.html?q=kl&check_keywords=yes&area=default).  They're much more robust than the older gdspy/Clipper-based ones

Based on your other issue you can try, for example:
```python
from phidl import Path
import phidl.path as pp
from phidl import quickplot as qp
import phidl.geometry as pg

P = pp.arc(radius = 10, angle = 90)
D = P.extrude(20)
D = pg.kl_boolean(D,None, operation = 'or')
qp(D)
```
