### ISSUE TITLE
Migrating from gdspy to gdstk

### ISSUE THREAD

**Issue by dolphingarlic** [amccaugh/phidl#209]
It seems that gdspy [is being deprecated](https://github.com/heitzmann/gdspy?tab=readme-ov-file#future-of-gdspy) in favor of [gdstk](https://heitzmann.github.io/gdstk/). Are there any plans to migrate phidl to use gdstk?

**Comment by amccaugh** [comment]
As of right now, no -- see the discussion at https://github.com/amccaugh/phidl/issues/140 and https://github.com/amccaugh/phidl/issues/163 .  The basic gist is (1) I personally don't have enough free time to make it happen, and (2) all else being equal, it would make more sense to migrate to the klayout backend.

That being said -- you're in luck. PHIDL has a spiritual successor which has already implemented the klayout backend, see: https://github.com/gdsfactory/gdsfactory as well as a whole host of other features.  The interface is based off phidl so it should be very, very familiar, with a few minor changes (e.g. `mydevice.xmin` becomes `mydevice.dxmin` and `Device` becomes `Component`)
