### ISSUE TITLE
Accept Pathlib.Path object as input to filename

### ISSUE THREAD

**Issue by gyger** [amccaugh/phidl#74]
It would be nice if write_gds accept a Path object. 
See also the fix in gdspy (https://github.com/heitzmann/gdspy/commit/4c793fe36888894702270d37a29f2e0c0b80e136) and https://github.com/heitzmann/gdspy/issues/135.

**Comment by amccaugh** [comment]
I believe this is fixed in https://github.com/amccaugh/phidl/commit/16f288ca4e3fed0aae97aa0f01416f08817daf89 , would you be able to check @gyger ?

**Comment by gyger** [comment]
Works for me.
