### ISSUE TITLE
switching from gdspy to gdstk?

### ISSUE THREAD

**Issue by joamatab** [amccaugh/phidl#79]
Hi Adam,

gdspy is being rewritten to speed up manipulating larger layouts

I was wondering if you had any plans to switch from gdspy to gdstk ^^
https://github.com/heitzmann/gdstk

**Comment by amccaugh** [comment]
Hi Joaquin,

I think what will likely happen is that phidl 2.0 will allow you to choose either gdstk or klayout as a backend for certain operations (like `boolean` and `write_gds`). Most everything else will remain in Python likely -- my preliminary tests with using klayout as a backend found that there was a lot of Python->C computational overhead.  Converting objects back and forth between the two languages often made operations 10x slower than they would've been just in Python, and while there were ways around that in certain cases (like keeping everything in C the whole time), they required a LOT of code restructuring for a pretty minimal performance gain.  That's just my guess right now, I'll take a look at some point in the future -- I would definitely love to be proven wrong and have easy performance gains!
