### ISSUE TITLE
label ports not being used

### ISSUE THREAD

**Issue by joamatab** [amccaugh/phidl#97]
Hi Adam,

thank you for your your new phidl update

I noticed that label ports are passed to the set_quickplot_options but  not being used

```
def set_quickplot_options(show_ports = None, show_subports = None,
              label_ports = None, label_aliases = None, new_window = None,
              blocking = None, zoom_factor = None):
```

**Comment by amccaugh** [comment]
Thanks for finding this @joamatab , I've corrected it in d9ae4fc
